spring:
  # MYSQL
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost/vhr?serverTimezone=UTC
    username: root
    password: 123456
  # Redis
  redis:
    port: 6379
    database: 0
    host: 192.168.10.131
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1ms
        max-idle: 8
  # CACHE
  cache:
    cache-names: menus_cache
    redis:
      time-to-live: 1800s

# MyBatis
mybatis:
  mapper-locations: classpath*:/mappers/*.xml
# port
server:
  port: 8082